name: Tests
on: [push]
jobs:
  tests:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: package deps
        run: sudo apt-get install kyototycoon libkyototycoon-dev tokyotyrant libtokyotyrant-dev
      - name: pip deps
        run: |
          pip install cython msgpack-python
          python setup.py build_ext -i
      - name: runtests
        run: python tests.py
